apiVersion: v1
kind: Namespace
metadata:
  name: deployments-ns-94
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-sleep-94-deployment
  namespace: deployments-ns-94
  labels:
    app: busybox-sleep-94
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox-sleep-94
  template:
    metadata:
      labels:
        app: busybox-sleep-94
    spec:    
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
            name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-sleep-94-service
  namespace: deployments-ns-94
spec:
  selector:
    app: busybox-sleep-94
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
