apiVersion: v1
kind: Namespace
metadata:
  name: deployments-ns-79
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-sleep-79-deployment
  namespace: deployments-ns-79
  labels:
    app: busybox-sleep-79
spec:
  replicas: 6
  selector:
    matchLabels:
      app: busybox-sleep-79
  template:
    metadata:
      labels:
        app: busybox-sleep-79
    spec:    
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
            name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-sleep-79-service
  namespace: deployments-ns-79
spec:
  selector:
    app: busybox-sleep-79
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
