apiVersion: v1
kind: Namespace
metadata:
  name: deployments-ns-88
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-sleep-88-deployment
  namespace: deployments-ns-88
  labels:
    app: busybox-sleep-88
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox-sleep-88
  template:
    metadata:
      labels:
        app: busybox-sleep-88
    spec:    
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
            name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-sleep-88-service
  namespace: deployments-ns-88
spec:
  selector:
    app: busybox-sleep-88
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
