apiVersion: v1
kind: Namespace
metadata:
  name: deployments-ns-73
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-sleep-73-deployment
  namespace: deployments-ns-73
  labels:
    app: busybox-sleep-73
spec:
  replicas: 6
  selector:
    matchLabels:
      app: busybox-sleep-73
  template:
    metadata:
      labels:
        app: busybox-sleep-73
    spec:    
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
            name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-sleep-73-service
  namespace: deployments-ns-73
spec:
  selector:
    app: busybox-sleep-73
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
