apiVersion: v1
kind: Namespace
metadata:
  name: deployments-ns-28
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-sleep-28-deployment
  namespace: deployments-ns-28
  labels:
    app: busybox-sleep-28
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox-sleep-28
  template:
    metadata:
      labels:
        app: busybox-sleep-28
    spec:    
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
            name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-sleep-28-service
  namespace: deployments-ns-28
spec:
  selector:
    app: busybox-sleep-28
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
