apiVersion: v1
kind: Namespace
metadata:
  name: deployments-ns-18
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-sleep-18-deployment
  namespace: deployments-ns-18
  labels:
    app: busybox-sleep-18
spec:
  replicas: 6
  selector:
    matchLabels:
      app: busybox-sleep-18
  template:
    metadata:
      labels:
        app: busybox-sleep-18
    spec:    
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
            name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-sleep-18-service
  namespace: deployments-ns-18
spec:
  selector:
    app: busybox-sleep-18
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
