apiVersion: v1
kind: Namespace
metadata:
  name: pod-ns-77
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-77
  namespace: pod-ns-77
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "1000000"
