apiVersion: v1
kind: Namespace
metadata:
  name: pod-ns-82
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-82
  namespace: pod-ns-82
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "1000000"
